### ISSUE TITLE
巨大的Bug

### ISSUE THREAD

**Issue by dnknn** [iccfish/netdisk-helper#10]
# 此为测试 请看2楼解析此Bug🐞
https://cloud.189.cn/t/rmYN7zEbqq6z#c4ra 访问码c4ra
https://pan.baidu.com/s/13Lc_f4HQkbE_n3DMEZKRHQ 提取码sacb

测试...⛨🐞Debug

**Comment by dnknn** [comment]
![1171103](https://user-images.githubusercontent.com/10995302/92899993-e2a1bc00-f451-11ea-88d9-b81571aaef4b.png)

**Comment by iccfish** [comment]
收到，应该是构造HTML代码方面的问题，晚些时候我再看下。
