### ISSUE TITLE
作者您好，最近百度云的分享链接换格式了。

### ISSUE THREAD

**Issue by MrEbonycat** [iccfish/netdisk-helper#7]
来源：https://greasyfork.org/zh-CN/forum/discussion/35036/x
原帖作者：Wishmaster

举个例子 ：
链接: https://pan.baidu.com/s/1JHYvU9pOm-Xocq_g9j6o0Q 密码: 3ywu
脚本会把链接处理成 https://pan.baidu.com/s/1JHYvU9pOm#3ywu

像这种链接打开后会提示页面不存在。

**Comment by iccfish** [comment]
已更新，感谢报告。
