### ISSUE TITLE
发布时能否注释掉console.log呢, 谢谢 ?

### ISSUE THREAD

**Issue by mike652638** [iccfish/netdisk-helper#9]
您好, 谢谢您的脚本 :)
只是有个小小的请求: 能否在发布时注释掉#75, #106等行的 console.log("[网盘提取工具] 已处理网盘地址，URL=" + url + "，提取码=" + code + "模式：TEXTNODE");呢 ? 
因为经常需要用到F12开发者模式, 不相关的网站console面板也都出现这句话, 需要每次手动清空console或选择该网站不加载此脚本, 有些麻烦; 也试过自己到管理面板更改源码加上"//", 但每次你这边推送更新后又得弄一次 :)

**Comment by iccfish** [comment]
哦……好的……
